import esbuild from 'esbuild';
import process from 'node:process';
import { readFileSync } from 'node:fs';

const manifest = JSON.parse(readFileSync('./manifest.json', 'utf8'));
const production = process.argv[2] === 'production';

const banner = `/* Blockspace Workspace ${manifest.version} */
/*
THIS IS A GENERATED/BUNDLED FILE.
Source lives in src/*.cjs — do not hand-edit main.js.
*/
`;

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/plugin.cjs'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
  ],
  format: 'cjs',
  target: 'es2020',
  logLevel: 'info',
  sourcemap: production ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: production,
});

if (production) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
